// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: dkv.proto

package dkvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALRecord_Type int32

const (
	WALRecord_UNKNOWN         WALRecord_Type = 0
	WALRecord_ACCEPTOR_STATE  WALRecord_Type = 1
	WALRecord_COMMITTED_ENTRY WALRecord_Type = 2
)

// Enum value maps for WALRecord_Type.
var (
	WALRecord_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACCEPTOR_STATE",
		2: "COMMITTED_ENTRY",
	}
	WALRecord_Type_value = map[string]int32{
		"UNKNOWN":         0,
		"ACCEPTOR_STATE":  1,
		"COMMITTED_ENTRY": 2,
	}
)

func (x WALRecord_Type) Enum() *WALRecord_Type {
	p := new(WALRecord_Type)
	*p = x
	return p
}

func (x WALRecord_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALRecord_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_dkv_proto_enumTypes[0].Descriptor()
}

func (WALRecord_Type) Type() protoreflect.EnumType {
	return &file_dkv_proto_enumTypes[0]
}

func (x WALRecord_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALRecord_Type.Descriptor instead.
func (WALRecord_Type) EnumDescriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{14, 0}
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"` // "PUT", "GET", "DEL", "NOOP"
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     uint64                 `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_dkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Command) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Command) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type Ballot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	NodeId        uint32                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	mi := &file_dkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{1}
}

func (x *Ballot) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Ballot) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Ballot        *Ballot                `protobuf:"bytes,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Command       *Command               `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_dkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *LogEntry) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *Ballot                `protobuf:"bytes,1,opt,name=ballot,proto3" json:"ballot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_dkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareRequest) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

type PrepareResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PromisedBallot  *Ballot                `protobuf:"bytes,2,opt,name=promised_ballot,json=promisedBallot,proto3" json:"promised_ballot,omitempty"`
	AcceptedEntries []*AcceptedEntry       `protobuf:"bytes,3,rep,name=accepted_entries,json=acceptedEntries,proto3" json:"accepted_entries,omitempty"`
	LeaseActive     bool                   `protobuf:"varint,4,opt,name=lease_active,json=leaseActive,proto3" json:"lease_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_dkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PrepareResponse) GetPromisedBallot() *Ballot {
	if x != nil {
		return x.PromisedBallot
	}
	return nil
}

func (x *PrepareResponse) GetAcceptedEntries() []*AcceptedEntry {
	if x != nil {
		return x.AcceptedEntries
	}
	return nil
}

func (x *PrepareResponse) GetLeaseActive() bool {
	if x != nil {
		return x.LeaseActive
	}
	return false
}

type AcceptedEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Ballot        *Ballot                `protobuf:"bytes,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Command       *Command               `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedEntry) Reset() {
	*x = AcceptedEntry{}
	mi := &file_dkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedEntry) ProtoMessage() {}

func (x *AcceptedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedEntry.ProtoReflect.Descriptor instead.
func (*AcceptedEntry) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptedEntry) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AcceptedEntry) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptedEntry) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Ballot        *Ballot                `protobuf:"bytes,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Command       *Command               `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_dkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptRequest) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AcceptRequest) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type AcceptResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PromisedBallot *Ballot                `protobuf:"bytes,2,opt,name=promised_ballot,json=promisedBallot,proto3" json:"promised_ballot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_dkv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AcceptResponse) GetPromisedBallot() *Ballot {
	if x != nil {
		return x.PromisedBallot
	}
	return nil
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Command       *Command               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_dkv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{8}
}

func (x *CommitRequest) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CommitRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_dkv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{9}
}

type CatchupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterSlot     uint64                 `protobuf:"varint,1,opt,name=after_slot,json=afterSlot,proto3" json:"after_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupRequest) Reset() {
	*x = CatchupRequest{}
	mi := &file_dkv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupRequest) ProtoMessage() {}

func (x *CatchupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupRequest.ProtoReflect.Descriptor instead.
func (*CatchupRequest) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{10}
}

func (x *CatchupRequest) GetAfterSlot() uint64 {
	if x != nil {
		return x.AfterSlot
	}
	return 0
}

type CatchupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupResponse) Reset() {
	*x = CatchupResponse{}
	mi := &file_dkv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupResponse) ProtoMessage() {}

func (x *CatchupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupResponse.ProtoReflect.Descriptor instead.
func (*CatchupResponse) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{11}
}

func (x *CatchupResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      uint32                 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Ballot        *Ballot                `protobuf:"bytes,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	CommittedUpTo uint64                 `protobuf:"varint,3,opt,name=committed_up_to,json=committedUpTo,proto3" json:"committed_up_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_dkv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *HeartbeatRequest) GetBallot() *Ballot {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *HeartbeatRequest) GetCommittedUpTo() uint64 {
	if x != nil {
		return x.CommittedUpTo
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_dkv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WALRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           WALRecord_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=dkv.WALRecord_Type" json:"type,omitempty"`
	AcceptorState  *AcceptorStateRecord   `protobuf:"bytes,2,opt,name=acceptor_state,json=acceptorState,proto3" json:"acceptor_state,omitempty"`
	CommittedEntry *LogEntry              `protobuf:"bytes,3,opt,name=committed_entry,json=committedEntry,proto3" json:"committed_entry,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WALRecord) Reset() {
	*x = WALRecord{}
	mi := &file_dkv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALRecord) ProtoMessage() {}

func (x *WALRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALRecord.ProtoReflect.Descriptor instead.
func (*WALRecord) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{14}
}

func (x *WALRecord) GetType() WALRecord_Type {
	if x != nil {
		return x.Type
	}
	return WALRecord_UNKNOWN
}

func (x *WALRecord) GetAcceptorState() *AcceptorStateRecord {
	if x != nil {
		return x.AcceptorState
	}
	return nil
}

func (x *WALRecord) GetCommittedEntry() *LogEntry {
	if x != nil {
		return x.CommittedEntry
	}
	return nil
}

type AcceptorStateRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Slot           uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	PromisedBallot *Ballot                `protobuf:"bytes,2,opt,name=promised_ballot,json=promisedBallot,proto3" json:"promised_ballot,omitempty"`
	AcceptedBallot *Ballot                `protobuf:"bytes,3,opt,name=accepted_ballot,json=acceptedBallot,proto3" json:"accepted_ballot,omitempty"`
	AcceptedValue  *Command               `protobuf:"bytes,4,opt,name=accepted_value,json=acceptedValue,proto3" json:"accepted_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptorStateRecord) Reset() {
	*x = AcceptorStateRecord{}
	mi := &file_dkv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptorStateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptorStateRecord) ProtoMessage() {}

func (x *AcceptorStateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptorStateRecord.ProtoReflect.Descriptor instead.
func (*AcceptorStateRecord) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{15}
}

func (x *AcceptorStateRecord) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AcceptorStateRecord) GetPromisedBallot() *Ballot {
	if x != nil {
		return x.PromisedBallot
	}
	return nil
}

func (x *AcceptorStateRecord) GetAcceptedBallot() *Ballot {
	if x != nil {
		return x.AcceptedBallot
	}
	return nil
}

func (x *AcceptorStateRecord) GetAcceptedValue() *Command {
	if x != nil {
		return x.AcceptedValue
	}
	return nil
}

type SnapshotData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastIndex     uint64                 `protobuf:"varint,1,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	KvData        map[string]string      `protobuf:"bytes,2,rep,name=kv_data,json=kvData,proto3" json:"kv_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotData) Reset() {
	*x = SnapshotData{}
	mi := &file_dkv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotData) ProtoMessage() {}

func (x *SnapshotData) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotData.ProtoReflect.Descriptor instead.
func (*SnapshotData) Descriptor() ([]byte, []int) {
	return file_dkv_proto_rawDescGZIP(), []int{16}
}

func (x *SnapshotData) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

func (x *SnapshotData) GetKvData() map[string]string {
	if x != nil {
		return x.KvData
	}
	return nil
}

var File_dkv_proto protoreflect.FileDescriptor

const file_dkv_proto_rawDesc = "" +
	"\n" +
	"\tdkv.proto\x12\x03dkv\"}\n" +
	"\aCommand\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x04R\trequestId\"9\n" +
	"\x06Ballot\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\"m\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12#\n" +
	"\x06ballot\x18\x02 \x01(\v2\v.dkv.BallotR\x06ballot\x12&\n" +
	"\acommand\x18\x03 \x01(\v2\f.dkv.CommandR\acommand\"5\n" +
	"\x0ePrepareRequest\x12#\n" +
	"\x06ballot\x18\x01 \x01(\v2\v.dkv.BallotR\x06ballot\"\x96\x01\n" +
	"\x0fPrepareResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x124\n" +
	"\x0fpromised_ballot\x18\x02 \x01(\v2\v.dkv.BallotR\x0epromisedBallot\x12=\n" +
	"\x10accepted_entries\x18\x03 \x03(\v2\x12.dkv.AcceptedEntryR\x0facceptedEntries\"p\n" +
	"\rAcceptedEntry\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12#\n" +
	"\x06ballot\x18\x02 \x01(\v2\v.dkv.BallotR\x06ballot\x12&\n" +
	"\acommand\x18\x03 \x01(\v2\f.dkv.CommandR\acommand\"p\n" +
	"\rAcceptRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12#\n" +
	"\x06ballot\x18\x02 \x01(\v2\v.dkv.BallotR\x06ballot\x12&\n" +
	"\acommand\x18\x03 \x01(\v2\f.dkv.CommandR\acommand\"V\n" +
	"\x0eAcceptResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x124\n" +
	"\x0fpromised_ballot\x18\x02 \x01(\v2\v.dkv.BallotR\x0epromisedBallot\"K\n" +
	"\rCommitRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12&\n" +
	"\acommand\x18\x02 \x01(\v2\f.dkv.CommandR\acommand\"\x10\n" +
	"\x0eCommitResponse\"/\n" +
	"\x0eCatchupRequest\x12\x1d\n" +
	"\n" +
	"after_slot\x18\x01 \x01(\x04R\tafterSlot\":\n" +
	"\x0fCatchupResponse\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.dkv.LogEntryR\aentries\"|\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\rR\bleaderId\x12#\n" +
	"\x06ballot\x18\x02 \x01(\v2\v.dkv.BallotR\x06ballot\x12&\n" +
	"\x0fcommitted_up_to\x18\x03 \x01(\x04R\rcommittedUpTo\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xeb\x01\n" +
	"\tWALRecord\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.dkv.WALRecord.TypeR\x04type\x12?\n" +
	"\x0eacceptor_state\x18\x02 \x01(\v2\x18.dkv.AcceptorStateRecordR\racceptorState\x126\n" +
	"\x0fcommitted_entry\x18\x03 \x01(\v2\r.dkv.LogEntryR\x0ecommittedEntry\"<\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eACCEPTOR_STATE\x10\x01\x12\x13\n" +
	"\x0fCOMMITTED_ENTRY\x10\x02\"\xca\x01\n" +
	"\x13AcceptorStateRecord\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x124\n" +
	"\x0fpromised_ballot\x18\x02 \x01(\v2\v.dkv.BallotR\x0epromisedBallot\x124\n" +
	"\x0faccepted_ballot\x18\x03 \x01(\v2\v.dkv.BallotR\x0eacceptedBallot\x123\n" +
	"\x0eaccepted_value\x18\x04 \x01(\v2\f.dkv.CommandR\racceptedValue\"\xa0\x01\n" +
	"\fSnapshotData\x12\x1d\n" +
	"\n" +
	"last_index\x18\x01 \x01(\x04R\tlastIndex\x126\n" +
	"\akv_data\x18\x02 \x03(\v2\x1d.dkv.SnapshotData.KvDataEntryR\x06kvData\x1a9\n" +
	"\vKvDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9c\x02\n" +
	"\fDKVConsensus\x124\n" +
	"\aPrepare\x12\x13.dkv.PrepareRequest\x1a\x14.dkv.PrepareResponse\x121\n" +
	"\x06Accept\x12\x12.dkv.AcceptRequest\x1a\x13.dkv.AcceptResponse\x121\n" +
	"\x06Commit\x12\x12.dkv.CommitRequest\x1a\x13.dkv.CommitResponse\x124\n" +
	"\aCatchup\x12\x13.dkv.CatchupRequest\x1a\x14.dkv.CatchupResponse\x12:\n" +
	"\tHeartbeat\x12\x15.dkv.HeartbeatRequest\x1a\x16.dkv.HeartbeatResponseB\x1bZ\x19dkv/transport/proto/dkvpbb\x06proto3"

var (
	file_dkv_proto_rawDescOnce sync.Once
	file_dkv_proto_rawDescData []byte
)

func file_dkv_proto_rawDescGZIP() []byte {
	file_dkv_proto_rawDescOnce.Do(func() {
		file_dkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dkv_proto_rawDesc), len(file_dkv_proto_rawDesc)))
	})
	return file_dkv_proto_rawDescData
}

var file_dkv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dkv_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_dkv_proto_goTypes = []any{
	(WALRecord_Type)(0),         // 0: dkv.WALRecord.Type
	(*Command)(nil),             // 1: dkv.Command
	(*Ballot)(nil),              // 2: dkv.Ballot
	(*LogEntry)(nil),            // 3: dkv.LogEntry
	(*PrepareRequest)(nil),      // 4: dkv.PrepareRequest
	(*PrepareResponse)(nil),     // 5: dkv.PrepareResponse
	(*AcceptedEntry)(nil),       // 6: dkv.AcceptedEntry
	(*AcceptRequest)(nil),       // 7: dkv.AcceptRequest
	(*AcceptResponse)(nil),      // 8: dkv.AcceptResponse
	(*CommitRequest)(nil),       // 9: dkv.CommitRequest
	(*CommitResponse)(nil),      // 10: dkv.CommitResponse
	(*CatchupRequest)(nil),      // 11: dkv.CatchupRequest
	(*CatchupResponse)(nil),     // 12: dkv.CatchupResponse
	(*HeartbeatRequest)(nil),    // 13: dkv.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 14: dkv.HeartbeatResponse
	(*WALRecord)(nil),           // 15: dkv.WALRecord
	(*AcceptorStateRecord)(nil), // 16: dkv.AcceptorStateRecord
	(*SnapshotData)(nil),        // 17: dkv.SnapshotData
	nil,                         // 18: dkv.SnapshotData.KvDataEntry
}
var file_dkv_proto_depIdxs = []int32{
	2,  // 0: dkv.LogEntry.ballot:type_name -> dkv.Ballot
	1,  // 1: dkv.LogEntry.command:type_name -> dkv.Command
	2,  // 2: dkv.PrepareRequest.ballot:type_name -> dkv.Ballot
	2,  // 3: dkv.PrepareResponse.promised_ballot:type_name -> dkv.Ballot
	6,  // 4: dkv.PrepareResponse.accepted_entries:type_name -> dkv.AcceptedEntry
	2,  // 5: dkv.AcceptedEntry.ballot:type_name -> dkv.Ballot
	1,  // 6: dkv.AcceptedEntry.command:type_name -> dkv.Command
	2,  // 7: dkv.AcceptRequest.ballot:type_name -> dkv.Ballot
	1,  // 8: dkv.AcceptRequest.command:type_name -> dkv.Command
	2,  // 9: dkv.AcceptResponse.promised_ballot:type_name -> dkv.Ballot
	1,  // 10: dkv.CommitRequest.command:type_name -> dkv.Command
	3,  // 11: dkv.CatchupResponse.entries:type_name -> dkv.LogEntry
	2,  // 12: dkv.HeartbeatRequest.ballot:type_name -> dkv.Ballot
	0,  // 13: dkv.WALRecord.type:type_name -> dkv.WALRecord.Type
	16, // 14: dkv.WALRecord.acceptor_state:type_name -> dkv.AcceptorStateRecord
	3,  // 15: dkv.WALRecord.committed_entry:type_name -> dkv.LogEntry
	2,  // 16: dkv.AcceptorStateRecord.promised_ballot:type_name -> dkv.Ballot
	2,  // 17: dkv.AcceptorStateRecord.accepted_ballot:type_name -> dkv.Ballot
	1,  // 18: dkv.AcceptorStateRecord.accepted_value:type_name -> dkv.Command
	18, // 19: dkv.SnapshotData.kv_data:type_name -> dkv.SnapshotData.KvDataEntry
	4,  // 20: dkv.DKVConsensus.Prepare:input_type -> dkv.PrepareRequest
	7,  // 21: dkv.DKVConsensus.Accept:input_type -> dkv.AcceptRequest
	9,  // 22: dkv.DKVConsensus.Commit:input_type -> dkv.CommitRequest
	11, // 23: dkv.DKVConsensus.Catchup:input_type -> dkv.CatchupRequest
	13, // 24: dkv.DKVConsensus.Heartbeat:input_type -> dkv.HeartbeatRequest
	5,  // 25: dkv.DKVConsensus.Prepare:output_type -> dkv.PrepareResponse
	8,  // 26: dkv.DKVConsensus.Accept:output_type -> dkv.AcceptResponse
	10, // 27: dkv.DKVConsensus.Commit:output_type -> dkv.CommitResponse
	12, // 28: dkv.DKVConsensus.Catchup:output_type -> dkv.CatchupResponse
	14, // 29: dkv.DKVConsensus.Heartbeat:output_type -> dkv.HeartbeatResponse
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_dkv_proto_init() }
func file_dkv_proto_init() {
	if File_dkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dkv_proto_rawDesc), len(file_dkv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dkv_proto_goTypes,
		DependencyIndexes: file_dkv_proto_depIdxs,
		EnumInfos:         file_dkv_proto_enumTypes,
		MessageInfos:      file_dkv_proto_msgTypes,
	}.Build()
	File_dkv_proto = out.File
	file_dkv_proto_goTypes = nil
	file_dkv_proto_depIdxs = nil
}
