// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: dkv.proto

package dkvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DKVConsensus_Prepare_FullMethodName   = "/dkv.DKVConsensus/Prepare"
	DKVConsensus_Accept_FullMethodName    = "/dkv.DKVConsensus/Accept"
	DKVConsensus_Commit_FullMethodName    = "/dkv.DKVConsensus/Commit"
	DKVConsensus_Catchup_FullMethodName   = "/dkv.DKVConsensus/Catchup"
	DKVConsensus_Heartbeat_FullMethodName = "/dkv.DKVConsensus/Heartbeat"
)

// DKVConsensusClient is the client API for DKVConsensus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DKVConsensusClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	Catchup(ctx context.Context, in *CatchupRequest, opts ...grpc.CallOption) (*CatchupResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type dKVConsensusClient struct {
	cc grpc.ClientConnInterface
}

func NewDKVConsensusClient(cc grpc.ClientConnInterface) DKVConsensusClient {
	return &dKVConsensusClient{cc}
}

func (c *dKVConsensusClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, DKVConsensus_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVConsensusClient) Accept(ctx context.Context, in *AcceptRequest, opts ...grpc.CallOption) (*AcceptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptResponse)
	err := c.cc.Invoke(ctx, DKVConsensus_Accept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVConsensusClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, DKVConsensus_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVConsensusClient) Catchup(ctx context.Context, in *CatchupRequest, opts ...grpc.CallOption) (*CatchupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatchupResponse)
	err := c.cc.Invoke(ctx, DKVConsensus_Catchup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKVConsensusClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, DKVConsensus_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DKVConsensusServer is the server API for DKVConsensus service.
// All implementations must embed UnimplementedDKVConsensusServer
// for forward compatibility.
type DKVConsensusServer interface {
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	Accept(context.Context, *AcceptRequest) (*AcceptResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	Catchup(context.Context, *CatchupRequest) (*CatchupResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedDKVConsensusServer()
}

// UnimplementedDKVConsensusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDKVConsensusServer struct{}

func (UnimplementedDKVConsensusServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedDKVConsensusServer) Accept(context.Context, *AcceptRequest) (*AcceptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedDKVConsensusServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedDKVConsensusServer) Catchup(context.Context, *CatchupRequest) (*CatchupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Catchup not implemented")
}
func (UnimplementedDKVConsensusServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDKVConsensusServer) mustEmbedUnimplementedDKVConsensusServer() {}
func (UnimplementedDKVConsensusServer) testEmbeddedByValue()                      {}

// UnsafeDKVConsensusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DKVConsensusServer will
// result in compilation errors.
type UnsafeDKVConsensusServer interface {
	mustEmbedUnimplementedDKVConsensusServer()
}

func RegisterDKVConsensusServer(s grpc.ServiceRegistrar, srv DKVConsensusServer) {
	// If the following call panics, it indicates UnimplementedDKVConsensusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DKVConsensus_ServiceDesc, srv)
}

func _DKVConsensus_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVConsensusServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKVConsensus_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVConsensusServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKVConsensus_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVConsensusServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKVConsensus_Accept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVConsensusServer).Accept(ctx, req.(*AcceptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKVConsensus_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVConsensusServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKVConsensus_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVConsensusServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKVConsensus_Catchup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatchupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVConsensusServer).Catchup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKVConsensus_Catchup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVConsensusServer).Catchup(ctx, req.(*CatchupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKVConsensus_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKVConsensusServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DKVConsensus_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKVConsensusServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DKVConsensus_ServiceDesc is the grpc.ServiceDesc for DKVConsensus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DKVConsensus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dkv.DKVConsensus",
	HandlerType: (*DKVConsensusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _DKVConsensus_Prepare_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _DKVConsensus_Accept_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _DKVConsensus_Commit_Handler,
		},
		{
			MethodName: "Catchup",
			Handler:    _DKVConsensus_Catchup_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DKVConsensus_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dkv.proto",
}
